AFN_base:
    model: AFN
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    logarithmic_neurons: 1200
    afn_hidden_units: [400, 400, 400]
    afn_activations: relu
    afn_dropout: 0
    ensemble_dnn: False
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    dnn_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
AFN_Criteo_x4_46m:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 5000
    data_root: './data/Criteo/'
    dataset_id: Criteo_x4_46m
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    seed: 2022
    shuffle: true
    task: binary_classification
AFN_avazu_x4:
    afn_activations: relu
    afn_dropout: 0
    afn_hidden_units: [1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: Avazu_x4
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Avazu/AFN_avazu_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 0
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3