DCN_Criteo_x4_46m:
    model: DCN
    dataset_id: Criteo_x4_46m
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 1.0e-05
    net_regularizer: 0
    batch_size: 5000
    embedding_dim: 16
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    dnn_activations: relu
    crossing_layers: 4
    net_dropout: 0.2
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
DCN_avazu_x4:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 3
    dataset_id: Avazu_x4
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [2000, 2000, 2000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 0
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3