PNN_Criteo_x4_46m:
    batch_norm: false
    batch_size: 5000
    dataset_id: Criteo_x4_46m
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_avazu_x4:
    batch_norm: false
    batch_size: 10000
    dataset_id: Avazu_x4
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Avazu/PNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 0
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3