xDeepFM_Criteo_x4_46m:
    batch_norm: false
    batch_size: 5000
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_46m
    debug: false
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4:
    batch_norm: false
    batch_size: 5000
    cin_layer_units: [276]
    dataset_id: Avazu_x4
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 0
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3