### Criteo dataset
Criteo_x4_0.6m:
    data_root: data/Criteo/
    data_format: csv
    train_data: data/Criteo/Criteo_x4_0.6m/train.csv
    valid_data: data/Criteo/Criteo_x4_0.6m/valid.csv
    test_data: data/Criteo/Criteo_x4_0.6m/test.csv
    min_categr_count: 10
    data_block_size: -1
    feature_cols:
        - {name: [I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13],
           active: True, dtype: float, type: categorical, preprocess: convert_to_bucket, na_value: 0}
        - {name: [C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26],
           active: True, dtype: str, type: categorical, na_value: ""}
    label_col: {name: Label, dtype: float}

Criteo_x4_46m:
    data_root: data/Criteo/
    data_format: csv
    train_data: data/Criteo/Criteo_x4_46m/train.csv
    valid_data: data/Criteo/Criteo_x4_46m/valid.csv
    test_data: data/Criteo/Criteo_x4_46m/test.csv
    min_categr_count: 10
    data_block_size: -1
    feature_cols:
        - {name: [I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13],
           active: True, dtype: float, type: categorical, preprocess: convert_to_bucket, na_value: 0}
        - {name: [C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26],
           active: True, dtype: str, type: categorical, na_value: ""}
    label_col: {name: Label, dtype: float}