### Frappe dataset 
Frappe:
    data_root: data/
    data_format: csv
    train_data: data/Frappe/train.csv
    valid_data: data/Frappe/valid.csv
    test_data: data/Frappe/test.csv
    min_categr_count: 2
    data_block_size: -1
    feature_cols:
        - {name: [user, item, daytime, weekday, isweekend, homework, cost, weather, country, city], 
           active: True, dtype: str, type: categorical, na_value: ""}
    label_col: {name: label, dtype: float}
